ENABLED = "yes"

[SETTINGS]
URL_PREFIX = "/"
#SUBDOMAIN = ""
#URL_DEFAULTS = {}
STATIC_FOLDER = "static"
TEMPLATE_FOLDER = "templates"
STATIC_URL_PATH = "/static"
#ROOT_PATH = ""
#CLI_GROUP = ""

[SESSION]
#www_session = "yes"

# Set ENABLED to true to allow the blueprint
# to create a database bind, change settings accordingly.
[DATABASE_BIND]
ENABLED = false
DIALECT = "sqlite"
DATABASE_NAME = "www"
LOCATION = ""
PORT = ""
USERNAME = ""
PASSWORD = ""
