enabled = "yes"

[settings]
url_prefix = "/www"
subdomain = ""
url_defaults = { }
#static_folder = "static"
template_folder = "templates"
static_url_path = "/www/static"

[session]
www_session = "yes"
